# Generated by Django 5.0.8 on 2024-08-31 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgptbot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Messages History', 'verbose_name_plural': 'Messages History'},
        ),
        migrations.AddField(
            model_name='chatgptbot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
